### PR TITLE
Allow running in background

### PR DESCRIPTION
**Pull request by krishvoor**
This PR will allow users to run in background.

### CODE REVIEW

**Comment by krishvoor** [comment]
Hi 👋 @chentex @jtaleric ptal

**Review by jtaleric — COMMENTED** [review]
Curious why we would want to run in the background?

**Comment by krishvoor** [comment]
> Curious why we would want to run in the background?

I plan to integrate this for a use case involving aws spot instances
when a spot instance/machinepool goes down and `rlgl` runs in the background.
I can act accordingly and bring up aws on-demand nodes.

**Comment by jtaleric** [comment]
> > Curious why we would want to run in the background?
> 
> I plan to integrate this for a use case involving aws spot instances when a spot instance/machinepool goes down and `rlgl` runs in the background. I can act accordingly and bring up aws on-demand nodes.

🤔 

> I can act accordingly and bring up aws on-demand nodes.

If a spot-instance gets reaped, will ocp not simply spin up a new spot-instance in that machinepool?

**Comment by krishvoor** [comment]
>> I can act accordingly and bring up aws on-demand nodes.

>If a spot instance gets reaped, will ocp not simply spin up a new spot instance in that machinepool

Each spot-instance-based machinepool is associated with `spot-max-price` parameter.
Simply put, whoever bids higher will retain them for a longer duration. 
OCP will attempt to spin up instances from the same machinepool config, 
but may not get it, as someone already took it by bidding higher `spot-max-price`

**Comment by jtaleric** [comment]
> > > I can act accordingly and bring up aws on-demand nodes.
> 
> > If a spot instance gets reaped, will ocp not simply spin up a new spot instance in that machinepool
> 
> Each spot-instance-based machinepool is associated with `spot-max-price` parameter. Simply put, whoever bids higher will retain them for a longer duration. OCP will attempt to spin up instances from the same machinepool config, but may not get it, as someone already took it by bidding higher `spot-max-price`

ack - ok, so it isn't a simple machinepool was reduced, and it tries to reconcile that difference. 

I am not opposed to this change, it just wasn't something I think we would want to do with rlgl...

**Comment by krishvoor** [comment]
>I am not opposed to this change, it just wasn't something I think we would want to do with rlgl...

I hear you, this PR proved useful when I wanted to actively monitor Bad Events happening at the cluster level 
rather than periodically checking, do you have other suggestions?

**Comment by jtaleric** [comment]
> > I am not opposed to this change, it just wasn't something I think we would want to do with rlgl...
> 
> I hear you, this PR proved useful when I wanted to actively monitor Bad Events happening at the cluster level rather than periodically checking, do you have other suggestions?

I guess I am curious how you are going to consume the message from rlgl -- it is just spitting stuff to the console... it would almost need to have a message bus of some-sort to notify that the event happened.

**Comment by krishvoor** [comment]
>I guess I am curious how you are going to consume the message from rlgl -- it is just spitting stuff to the console... it would almost need to have a message bus of some-sort to notify that the event happened.

Right, this is what I am planning to do:
1. Redirect the `rlgl --background` output to a log file
2. Create a `watcher` on the log file for a particular event and notify when the corresponding event happens.

I am yet to play with the above and eventually plan to spin up instances via airflow DAG.

**Pull request merged**
